#!/usr/bin/env bash

set -o nounset
set -o errexit

if [[ -d "debug" ]]; then
  echo "Using parser debug/parser/"
  PARSER="debug/TestCPP"
else
  echo "Using parser in bin/parser/"
  PARSER="bin/TestCPP"
fi

FILES=$@
if [[ $# -eq 0 ]]; then
  FILES=`ls tests/`
fi

for testCase in $FILES
do
  if [ "$testCase" != "reject" ]; then
    echo "======== TEST CASE $testCase ========"
    $PARSER "tests/$testCase"
  fi
done

if [[ $# -eq 0 ]]; then
  REJ_FILES=`ls tests/reject/`
  for testCase in $REJ_FILES
  do
    echo "======== REJECT TEST CASE $testCase ========"
    set +e
    $PARSER "tests/reject/$testCase"
    retCode=$?
    set -e

    if [[ $retCode -eq 0 ]]; then
      echo "Reject test case passed!"
      exit 1
    fi
  done
fi


echo ""
echo "All tests passed successfully!"